## Section 1

In [77]:
import pandas as pd
import numpy as np

#Q1

price = np.array([250, 180, 90, 340, 120])
print(type(price))

zeroes = np.zeros(6) #array of 6 zeroes:
ones = np.ones(6)

lists = np.arange(0,50+1,5)
print(lists)
spaced_no = np.linspace(0,1,6)
print(spaced_no)

#Q2
print(f"shape of price array: {price.shape}")
print(f"dimension of price array: {price.ndim}")
sales_grid = np.random.randint(1,13, size=(3,4), dtype=int)
print(f"sales_grid: {sales_grid}")
print(sales_grid.ndim) #  ndim 2 because the array is made of two dimensions( rows and column)

#Q3
print(price[0], price[-1]) #first value last value

print(price[0:4], price[1:5:2]) # 1-3 values

print(sales_grid[0][0], sales_grid[-1][-1])

print(f" first two rows of sales_grid {sales_grid[0:2]}")
print(f" first two columns of sales_grid {sales_grid[0][:2]}")



#Q4
b_price = np.multiply(price,0.15)
print(b_price)
quantities = [34,453,45,70,50]
print(np.multiply(price,quantities))

print(f"10% discount on sales_grid:\n{np.multiply(0.1,sales_grid)}")

#Q5

print(f""
      f"sum of prices: {sum(price)}\n"
      f"mean price: {np.mean(price)}\n"
      f"minimum price: {np.min(price)}\n"
      f"maximum price: {np.max(price)}\n"
      f"standard deviation of price: {np.std(price):.2f}")

print(sales_grid.sum(axis=1))
print(sales_grid.sum(axis=0))

array = np.arange(1,12+1)
array_reshaped = array.reshape(4,3)
print(array_reshaped)
print(f"shape before: {array.shape} \n ew shape: {array_reshaped.shape}")






<class 'numpy.ndarray'>
[ 0  5 10 15 20 25 30 35 40 45 50]
[0.  0.2 0.4 0.6 0.8 1. ]
shape of price array: (5,)
dimension of price array: 1
sales_grid: [[ 3  2  3  4]
 [10  2  4  5]
 [ 1  1  9  8]]
2
250 120
[250 180  90 340] [180 340]
3 8
 first two rows of sales_grid [[ 3  2  3  4]
 [10  2  4  5]]
 first two columns of sales_grid [3 2]
[37.5 27.  13.5 51.  18. ]
[ 8500 81540  4050 23800  6000]
10% discount on sales_grid:
[[0.3 0.2 0.3 0.4]
 [1.  0.2 0.4 0.5]
 [0.1 0.1 0.9 0.8]]
sum of prices: 980
mean price: 196.0
minimum price: 90
maximum price: 340
standard deviation of price: 90.47
[12 21 19]
[14  5 16 17]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape before: (12,) 
 ew shape: (4, 3)


## Section 2

In [78]:

#Q1
series = pd.Series([23, 25, 21, 27], index=["Michelangelo", "escobar", "negro san", "ruby"])
print(series)
print(f"the data type of this series is {series.dtype}")

Michelangelo    23
escobar         25
negro san       21
ruby            27
dtype: int64
the data type of this series is int64


In [79]:
#Q2
dict = {"players": ["Barcola", "florian", "van djik", "palmar"], "club": ["Liverpool", "Liverpool", "Liverpool", "Chelsea"], "rating": [6.7, 7.0, 7.5, 8.6]}

dataframe = pd.DataFrame(dict)

print(f"{dataframe}, \nDatatype: {type(dataframe)}")

    players       club  rating
0   Barcola  Liverpool     6.7
1   florian  Liverpool     7.0
2  van djik  Liverpool     7.5
3    palmar    Chelsea     8.6, 
Datatype: <class 'pandas.DataFrame'>


In [80]:
#Q3
dataframe.to_csv("Dataframe")
data = pd.read_csv("Dataframe")
print(data)
print(data.head(2))
print(data.tail(2))
print(data.shape)
print(data.columns.to_list())
print(data.info())
print(data.describe())

   Unnamed: 0   players       club  rating
0           0   Barcola  Liverpool     6.7
1           1   florian  Liverpool     7.0
2           2  van djik  Liverpool     7.5
3           3    palmar    Chelsea     8.6
   Unnamed: 0  players       club  rating
0           0  Barcola  Liverpool     6.7
1           1  florian  Liverpool     7.0
   Unnamed: 0   players       club  rating
2           2  van djik  Liverpool     7.5
3           3    palmar    Chelsea     8.6
(4, 4)
['Unnamed: 0', 'players', 'club', 'rating']
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  4 non-null      int64  
 1   players     4 non-null      str    
 2   club        4 non-null      str    
 3   rating      4 non-null      float64
dtypes: float64(1), int64(1), str(2)
memory usage: 260.0 bytes
None
       Unnamed: 0    rating
count    4.000000  4.000000
mean     1.500000  7

In [81]:
#Q4
print(data["players"])
print(type(data["players"]))
new_dataframe = data.iloc[:,:2]
print(type(new_dataframe))

0     Barcola
1     florian
2    van djik
3      palmar
Name: players, dtype: str
<class 'pandas.Series'>
<class 'pandas.DataFrame'>


In [82]:
#Q5
print(data.loc[0])
print(data.loc[0]["club"])
print(data.iloc[:1])
print(data.iloc[:2, :2])

Unnamed: 0            0
players         Barcola
club          Liverpool
rating              6.7
Name: 0, dtype: object
Liverpool
   Unnamed: 0  players       club  rating
0           0  Barcola  Liverpool     6.7
   Unnamed: 0  players
0           0  Barcola
1           1  florian


## Section 3

In [83]:

students = pd.DataFrame({
    "Name": [
        "Ada", "Tunde", "Mariam", "David", "Ayomide",
        "Emeka", "Sarah", "Daniel", "Aisha", "Michael"
    ],
    "Age": [
        20, 21, np.nan, 22, 18,
        23, 21, np.nan, 22, 24
    ],
    "Department": [
        "Computer Science", "Mathematics", "Computer Science", np.nan,
        "Software Engineering", "biology", "Mathematics", "Computer Science",
        np.nan, "Physics"
    ],
    "GPA": [
        4.5, np.nan, 4.2, 3.8, 4.7,
        np.nan, 4.1, 3.9, 4.6, 4.0
    ],
    "Level": [
        200, 300, 200, 400, 300,
        300, 200, 400, 300, np.nan
    ],
    "Scholarship": [
        "Yes", "No", np.nan, "No", "Yes",
        "No", "Yes", np.nan, "Yes", "No"
    ]
})

students

,Name,Age,Department,GPA,Level,Scholarship
0,Ada,20.0,Computer Science,4.5,200.0,Yes
1,Tunde,21.0,Mathematics,NaN,300.0,No
2,Mariam,NaN,Computer Science,4.2,200.0,NaN
3,David,22.0,NaN,3.8,400.0,No
4,Ayomide,18.0,Software Engineering,4.7,300.0,Yes
5,Emeka,23.0,biology,NaN,300.0,No
6,Sarah,21.0,Mathematics,4.1,200.0,Yes
7,Daniel,NaN,Computer Science,3.9,400.0,NaN
8,Aisha,22.0,NaN,4.6,300.0,Yes
9,Michael,24.0,Physics,4.0,NaN,No


In [84]:
#Q2
print(students.isnull())
print(f"total number of missing element: {students.isnull().sum().sum()}")
print(students.copy().dropna())
data = students.copy()
data["GPA"] = data["GPA"].fillna(data["GPA"].mean())
data["Level"] = data["Level"].fillna(data["Level"].median())
data["Scholarship"] = data["Scholarship"].replace(np.nan,"pending")
print(data)

    Name    Age  Department    GPA  Level  Scholarship
0  False  False       False  False  False        False
1  False  False       False   True  False        False
2  False   True       False  False  False         True
3  False  False        True  False  False        False
4  False  False       False  False  False        False
5  False  False       False   True  False        False
6  False  False       False  False  False        False
7  False   True       False  False  False         True
8  False  False        True  False  False        False
9  False  False       False  False   True        False
total number of missing element: 9
      Name   Age            Department  GPA  Level Scholarship
0      Ada  20.0      Computer Science  4.5  200.0         Yes
4  Ayomide  18.0  Software Engineering  4.7  300.0         Yes
6    Sarah  21.0           Mathematics  4.1  200.0         Yes
      Name   Age            Department    GPA  Level Scholarship
0      Ada  20.0      Computer Science  4.5

In [85]:
#Q3
Age_filter = data[data["Age"]< 23]
print(Age_filter)
print(f"\n\n")
scholarship_f = data[data["Scholarship"]=="pending"]
print(scholarship_f)
print(f"\n\n")
data_filtered = data[(data["GPA"]>4.49) & (data["Level"]>=100)]
print(f"\n\n")
print(data_filtered)

      Name   Age            Department    GPA  Level Scholarship
0      Ada  20.0      Computer Science  4.500  200.0         Yes
1    Tunde  21.0           Mathematics  4.225  300.0          No
3    David  22.0                   NaN  3.800  400.0          No
4  Ayomide  18.0  Software Engineering  4.700  300.0         Yes
6    Sarah  21.0           Mathematics  4.100  200.0         Yes
8    Aisha  22.0                   NaN  4.600  300.0         Yes



     Name  Age        Department  GPA  Level Scholarship
2  Mariam  NaN  Computer Science  4.2  200.0     pending
7  Daniel  NaN  Computer Science  3.9  400.0     pending






      Name   Age            Department  GPA  Level Scholarship
0      Ada  20.0      Computer Science  4.5  200.0         Yes
4  Ayomide  18.0  Software Engineering  4.7  300.0         Yes
8    Aisha  22.0                   NaN  4.6  300.0         Yes


In [86]:
#Q4
print(f"mean age: {data["Age"].mean()}")
print(f"median GPA: {data["GPA"].median()}")
print(f"standard deviation of GPA: {data['GPA'].std():.2f}")
print(data["Scholarship"].value_counts())
print(f"correlation between Age and level{data["Age"].corr(data["Level"]):.4f}")

mean age: 21.375
median GPA: 4.2125
standard deviation of GPA: 0.30
Scholarship
Yes        4
No         4
pending    2
Name: count, dtype: int64
correlation between Age and level0.2867


In [87]:
#Q5
sorted_data = data.sort_values(by="Age",ascending=False)
print(sorted_data)
print(f"\n\n")
print(data.groupby("Scholarship")["GPA"].mean())  #groupby create another set of dataframes internally based on the categories of scholarship then it looks for the mean GPA of dataframes/categories

      Name   Age            Department    GPA  Level Scholarship
9  Michael  24.0               Physics  4.000  300.0          No
5    Emeka  23.0               biology  4.225  300.0          No
3    David  22.0                   NaN  3.800  400.0          No
8    Aisha  22.0                   NaN  4.600  300.0         Yes
1    Tunde  21.0           Mathematics  4.225  300.0          No
6    Sarah  21.0           Mathematics  4.100  200.0         Yes
0      Ada  20.0      Computer Science  4.500  200.0         Yes
4  Ayomide  18.0  Software Engineering  4.700  300.0         Yes
2   Mariam   NaN      Computer Science  4.200  200.0     pending
7   Daniel   NaN      Computer Science  3.900  400.0     pending



Scholarship
No         4.0625
Yes        4.4750
pending    4.0500
Name: GPA, dtype: float64


## Section 4

In [88]:
#Q1
import pandas as pd
import numpy as np

titanic_dataset = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv")
print(titanic_dataset.shape)
print(titanic_dataset.columns)
print(titanic_dataset.dtypes)
print(titanic_dataset.isnull().sum())            # the deck columns has the highest missing values
print(titanic_dataset.head())

(891, 15)
Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')
survived         int64
pclass           int64
sex                str
age            float64
sibsp            int64
parch            int64
fare           float64
embarked           str
class              str
who                str
adult_male        bool
deck               str
embark_town        str
alive              str
alone             bool
dtype: object
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Thir

In [89]:
#Q2 & #Q3
print(titanic_dataset.describe())  #mean and max of the fare column: 32.204208, 512.329200 respectively
#considering the fact that the median is less than the mean iin a relatively large amount, the fare column values is skewed to the right
print(f"Survival rate: {titanic_dataset["survived"].mean():.2f}")
print(f"Passengers in each classes: {titanic_dataset['pclass'].value_counts()}")
print(f"Average Age of passengers: {titanic_dataset['age'].mean():.1f}")


         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200
Survival rate: 0.38
Passengers in each classes: pclass
3    491
1    216
2    184
Name: count, dtype: int64
Average Age of passengers: 29.7


In [90]:
#Q4
print(f"Survival rate by sex: {titanic_dataset.groupby("sex")["survived"].mean()}")
print(f"Survival rate by passenger class: {titanic_dataset.groupby("pclass")["survived"].mean()}")
#according to the results females and passengers in class 1 are more likely to survive

Survival rate by sex: sex
female    0.742038
male      0.188908
Name: survived, dtype: float64
Survival rate by passenger class: pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64


In [91]:
#Q5
print(f"Correlation between fare and survived: {titanic_dataset["fare"].corr(titanic_dataset["survived"]):.4f}")
print(f"Correlation between fare and passenger class: {titanic_dataset["pclass"].corr(titanic_dataset["fare"]):.4f}")
#I would expect pclass and fare to be negatively correlated because higher-class
# passengers pay higher fares. which is inversely proportional

Correlation between fare and survived: 0.2573
Correlation between fare and passenger class: -0.5495


# Project

In [92]:
#Q1
netflix_dataset = pd.read_csv("https://raw.githubusercontent.com/prasertcbs/basic-dataset/master/netflix_titles.csv")
print(netflix_dataset.shape)
netflix_dataset.info()
print(f"Sum of missing element in each column: {netflix_dataset.isnull().sum()}")

(6234, 12)
<class 'pandas.DataFrame'>
RangeIndex: 6234 entries, 0 to 6233
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       6234 non-null   int64
 1   type          6234 non-null   str  
 2   title         6234 non-null   str  
 3   director      4265 non-null   str  
 4   cast          5664 non-null   str  
 5   country       5758 non-null   str  
 6   date_added    6223 non-null   str  
 7   release_year  6234 non-null   int64
 8   rating        6224 non-null   str  
 9   duration      6234 non-null   str  
 10  listed_in     6234 non-null   str  
 11  description   6234 non-null   str  
dtypes: int64(2), str(10)
memory usage: 584.6 KB
Sum of missing element in each column: show_id            0
type               0
title              0
director        1969
cast             570
country          476
date_added        11
release_year       0
rating            10
duration           0
listed_in          0


In [93]:
#Q2
netflix_dataset_dup = netflix_dataset.copy()
netflix_dataset_dup.drop(columns="director", inplace=True)

netflix_dataset_dup["rating"] = netflix_dataset_dup["rating"].fillna("Not Rated")
netflix_dataset_dup["cast"] = netflix_dataset_dup["cast"].fillna("Unknown")
netflix_dataset_dup["country"] = netflix_dataset_dup["country"].fillna("Unknown")

netflix_dataset_dup.dropna(subset=["date_added"], inplace=True)

print(netflix_dataset_dup.isnull().sum())

show_id         0
type            0
title           0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64


In [94]:
#Q3
print(netflix_dataset_dup.head(5))
print(netflix_dataset_dup["duration"].describe())
print(netflix_dataset_dup["release_year"].describe())
print(netflix_dataset_dup["date_added"].describe())

    show_id     type                                    title  \
0  81145628    Movie  Norm of the North: King Sized Adventure   
1  80117401    Movie               Jandino: Whatever it Takes   
2  70234439  TV Show                       Transformers Prime   
3  80058654  TV Show         Transformers: Robots in Disguise   
4  80125979    Movie                             #realityhigh   

                                                cast  \
0  Alan Marriott, Andrew Toth, Brian Dobson, Cole...   
1                                   Jandino Asporaat   
2  Peter Cullen, Sumalee Montano, Frank Welker, J...   
3  Will Friedle, Darren Criss, Constance Zimmer, ...   
4  Nesta Cooper, Kate Walsh, John Michael Higgins...   

                                    country         date_added  release_year  \
0  United States, India, South Korea, China  September 9, 2019          2019   
1                            United Kingdom  September 9, 2016          2016   
2                             Un

In [95]:
#Q4
#statistics on duration column
movies = netflix_dataset_dup[netflix_dataset_dup["type"] == "Movie"]["duration"]
movies_mins = movies.str.replace(" min", "").astype(int)
print(f"Average movie duration: {movies_mins.mean():.2f} mins")

#year with highest release:
print(f"Year with highest release: {netflix_dataset_dup['release_year'].value_counts().index[0]}")

#number of release based on show type
print(netflix_dataset_dup["rating"].value_counts())


print(f"Cleaned dataset shape: {netflix_dataset_dup.shape}")




# The average movie duration of 99 mins since most movies usually between 1hr 2o min and 1hr 4o min

# 2018 being the year with the most releases makes sense since it was this moment were aggressive in their campaigns and trying to reach as much people as possible, this year also marked their first milestone in revenue

# TV-MA and TV-14 is the most common rating (2025 titles), which is expected since Netflix primarily targets adult and youth audiences.

Average movie duration: 99.11 mins
Year with highest release: 2018
rating
TV-MA        2025
TV-14        1695
TV-PG         699
R             508
PG-13         286
NR            217
PG            184
TV-Y7         168
TV-G          149
TV-Y          142
TV-Y7-FV       95
G              37
Not Rated       9
UR              7
NC-17           2
Name: count, dtype: int64
Cleaned dataset shape: (6223, 11)


In [96]:
#Q5

netflix_dataset_dup.to_csv("Netflix_dataset", index=False)

#what i did to the dataset:
#I dropped The 'director' column  because it had way too many missing values more than 20%
# For 'cast' and 'country', some titles genuinely don't have that info  available, so I filled those with 'Unknown' instead of losing the rows.
# 'rating' only had 9 missing values, so I filled those with 'Not Rated'
# 'date_added' had 11 missing rows — small enough to just drop without
# losing anything significant.
# For filtering, I checked that every row had a valid type — either 'Movie'
# or 'TV Show'. Nothing got removed, which just means the data was already
# clean on that front.